---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: userservice
  name: userservice
spec:
  selector:
    app: userservice
  ports:
  - name: userservice
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
